# Generated by Django 3.0.7 on 2020-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='post',
            field=models.CharField(choices=[('Dgsec', 'Department General Secretary'), ('Gsec', 'General Secretary (CSEA)'), ('pgrep', 'PG Represntative')], default='Dgsec', max_length=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
