# Generated by Django 3.0.7 on 2020-06-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200616_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='vote_count',
            new_name='vote',
        ),
    ]
