# Generated by Django 3.0.7 on 2020-06-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200616_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='vote',
            new_name='count',
        ),
    ]
